apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-cxgg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-cxgg
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-cxgg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-cxgg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-cxgg
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kajf-tenant/rhtap-demo-app/hacbs-test-project-cxgg@sha256:7535acf77c82685e1af0f654e7b6964f36095290f62470dfd2d154c1fd901e28
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
