apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-cxgg
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kajf-tenant/rhtap-demo-app/hacbs-test-project-cxgg@sha256:8d88d60a007a29cd5b341f2d4fbf87ecbdc1fcfd58c3cd901759151035f3d781
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
