apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-cxgg
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kajf-tenant/rhtap-demo-app/hacbs-test-project-cxgg@sha256:7535acf77c82685e1af0f654e7b6964f36095290f62470dfd2d154c1fd901e28
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
